### ISSUE TITLE
Update to newest versions of Forge?

### ISSUE THREAD

**Issue by wolflord212312** [KaiKikuchi/ServerRedirect#10]
Just wondering if you will update it to newer versions or if this project has been ditched

**Comment by KaiKikuchi** [comment]
Unfortunately, this project hasn't been adopted by most server networks and modpack developers.

Still, I think this project is easy to update to newer versions of Forge.

**Comment by Ezkimoo** [comment]
so will you do it or are you just saying that someone could do it. Because in the newer version of forge doesn't support proxy servers anymore. If this Mod would get an update for 1.16 it would be the only option to pull this off. I am working on a project and it would be pretty sick if this mod would work

**Comment by KaiKikuchi** [comment]
It sucks to hear that currently there's missing proxy support. Personally, I believe that something like ServerRedirect (so, a /redirect command) should be included in Forge without the need of a mod like this one.

This project is MIT licensed and anyone can do pretty much anything with the code in this repository.

I am not involved into Forge servers anymore, so I don't have a reason to spend time into updating this to the latest version at this moment. I'm too busy with my work.

**Comment by Ezkimoo** [comment]
okey thank you very much

**Comment by KaiKikuchi** [comment]
As the Pixelmon mod is going to be updated to Minecraft 1.16.5, I've started developing a new version of Server Redirect for the newer versions of Minecraft (in particular, 1.16.5). The new version of Server Redirect will be incompatible with Server Redirect 1.3.8 and lower, so you will have to update all your servers and clients to the newer version that will come out soon.

**Comment by KaiKikuchi** [comment]
Version 1.4 has been released, supporting Forge 1.16.5 and 1.18.1:
https://github.com/KaiKikuchi/ServerRedirect/releases/tag/v.1.4
