### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by felipeleite5w** [KaiKikuchi/ServerRedirect#13]
Hi, sorry for opening a issue but i need to talk to you about a Fix you did years ago, this is the link https://github.com/Chicken-Bones/EnderStorage/issues/65

You fixed the error creating a jar, I used your jar but it is still crashing. The mod is just Server-side or it needs to be Client-side too? Thanks!

**Comment by KaiKikuchi** [comment]
Please do not open issues on projects that are totally unrelated to your issue.
