### ISSUE TITLE
Using /fallback causes the client to get redirected

### ISSUE THREAD

**Issue by mja00** [KaiKikuchi/ServerRedirect#14]
On Forge 1.18.2 using the /fallback command causes the client to immediately get redirected to the specified server. 

https://user-images.githubusercontent.com/11252574/165842386-2cd090fe-7a49-4421-93cc-9c4be10a6409.mp4

I will assume this is a bug since the mod's page says it should only send them to that server if they get forcibly disconnected.

**Comment by KaiKikuchi** [comment]
Thank you for reporting this bug

The bug affected 1.16.x and 1.18.x Forge versions of the Server Redirect mod, mostly due to a copy-paste mistake. This has been fixed in version 1.4.4.
As the bug is only present in the server-side version, clients do not need to be updated to version 1.4.4.
