### ISSUE TITLE
No Command on Fabric server

### ISSUE THREAD

**Issue by TheCherry** [KaiKikuchi/ServerRedirect#15]
Fabric: 1.18.2 - 0.14.5
Fabric API: 0.51.1

I installed the fabric Fabric 1.18.2 - v.1.4.3 version to my fabric server and fabric client.
But I don't have the command /redirect as OP, the console says ` Unknown or incomplete command, see below for error` and the command block don't work too.

Greetings

**Comment by KaiKikuchi** [comment]
Hello, Fabric servers are currently not supported. Support for it is planned. Hopefully I can find some time to develop it.

**Comment by KaiKikuchi** [comment]
Fabric server support added in v.1.4.4
