### ISSUE TITLE
Unable to connect to velocity

### ISSUE THREAD

**Issue by ZeroJoKkkk** [KaiKikuchi/ServerRedirect#16]
I in the paper server use the command "redirect" ,cannot get into velocity.
But all my sub servers in velocity are fabric,In addition, velocity and fabric also have plugins and mod installed.
Sorry, I don't know what happened.I can't get any logs

**Comment by KaiKikuchi** [comment]
Hello. Please say what command you are running exactly. Not just "redirect", but the actual command you are running. Please notice that you have to use a *server address* with the redirect command, not just the server name. Your paper servers must have a direct connect address for Server Redirect to work as intended.

**Comment by ZeroJoKkkk** [comment]
Thank you for your reply. I found the problem. I forgot to install mod on the client. Therefore, all instructions cannot be used normally.
