### ISSUE TITLE
1.19 Bukkit compatibility

### ISSUE THREAD

**Issue by cjtganzon** [KaiKikuchi/ServerRedirect#19]
Hi! I use ServerRedirect 1.4.3 for bukkit and it doesn't seem to be working on 1.19.3

**Comment by KaiKikuchi** [comment]
Hi I just tested it on the latest version of Paper (server) and Forge 1.19.3 (client). It works fine.

Anything on the server and client logs?

**Comment by cjtganzon** [comment]
Sorry for the late reply. Probably my fault, not a version issue. Do I also need the mod to use ServerRedirect on bungeecord and bukkit servers? Edit: *backend bukkit servers

**Comment by KaiKikuchi** [comment]
If you are using Bukkit plugins or Command Blocks to run the /redirect command, have it on each backend Bukkit server. If you are using Bungee plugins to run the redirect command, have it on Bungeecord as well. You can just add it to both Bungee and Bukkit, as it is a very lightweight plugin anyway.

**Comment by cjtganzon** [comment]
Ah I do need the mod installed, should've read the FAQ. I do use GUI and NPC plugins to run the command so I put it on the backend Bukkit servers. Without the plugin on bungeecord though, it will not work. So I also put it on bungeecord and it works now! Thanks for your help!
