### ISSUE TITLE
[FEATURE REQUEST] Notify player when redirecting and more

### ISSUE THREAD

**Issue by Camawama** [KaiKikuchi/ServerRedirect#22]
Notify the player via Chat or Title message right before it redirects them.

This will ensure that players don't think they crashed when a larger modpack takes time to redirect. Players will hopefully see the pop-up right before it redirects them.

I was also wondering if there are ways to link servers together easier so you can pull players back from a server you have directed them to.

**Comment by KaiKikuchi** [comment]
> Notify the player via Chat or Title message right before it redirects them.
 
This cannot be done as Server Redirect detects the player has been disconnected from the server after the "game" screen gets removed (when the dirt background shows up).

Usually this happens quickly after something happens with the connection to the server, so if it takes such long time to redirect, there might be some mod doing something wrong.

**Comment by KaiKikuchi** [comment]
Sorry I thought you meant for the "fallback" feature. Actually, when it is just a normal redirect and not a fallback redirect, you can just make it so anything that triggers the redirect command to run a "tellraw" or "title" command before the redirect command so that would show in chat before the redirect happens. This is something that does not need to be added to Server Redirect.

**Comment by Camawama** [comment]
> Sorry I thought you meant for the "fallback" feature. Actually, when it is just a normal redirect and not a fallback redirect, you can just make it so anything that triggers the redirect command to run a "tellraw" or "title" command before the redirect command so that would show in chat before the redirect happens. This is something that does not need to be added to Server Redirect.

I see, my apologies. I think I have a pretty good idea of how to set this up!
