### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by chrgargar4** [KaiKikuchi/ServerRedirect#26]
Hi, i have 1 windows server with 2 users running 2 different servers, the first one has the minecraft port (25565) and the second has (25566). When trying to /redirect playername serverip:25566 i dont get kick or any error, it just doesnt do anything.

When loading the plugin i get a console error saying that it couldnt load plugin bcs plugin.yml not found but I can use the commands without getting any error.

It doesnt work on 1.19 or I've forgot to do something?

Thanks

**Comment by KaiKikuchi** [comment]
Hi sorry for the late reply.

You need to post your console log with all the errors so I can figure it out. It is very likely you're doing something wrong, as this works for me and several other people with 1.19.

**Comment by chrgargar4** [comment]
Hi, dont worry :).

I cant share console errors because it dont gives any error, I just use the command /redirect playername serverip:25566 and theres nothing more than my command when I see at the console.

I just read in your courseforge page that server needs to be online mode to work, since it doesnt specify in github page I tought it was no more necessary but i guess thats the reasson why is not working for me maybe?🤔

**Comment by KaiKikuchi** [comment]
Sorry for the late reply.

You said this:
> When loading the plugin i get a console error saying that it couldnt load plugin bcs plugin.yml not found

I'm confused if you get an error or not!

The server doesn't have to be in online mode, but you afaik you still cannot use 1.13+ proxies with Server Redirect, so you still have to set your 1.13 server config to online-mode.
