### ISSUE TITLE
Failed to connect to other servers after entering commands.

### ISSUE THREAD

**Issue by FnTlv** [KaiKikuchi/ServerRedirect#28]
This is the client log.
https://pastes.dev/XZ7mQRx2tw

It seems that the command is entered once and executed twice?

More information:
 * Minecraft version: 1.7.10
 * Forge version: 1.7.10-10.13.4.1614-1.7.10
 * Server version: Crucible-1.7.10-staging-81fcb90b-server

**Comment by KaiKikuchi** [comment]
Hey, I've just tried with the configuration you mentioned and couldn't reproduce the issue.

I've tried both the plugin version and the mod version of ServerRedirect on the server. Make sure you only use one of the two. If you are using the mod on your server, try the plugin instead. If you are using the plugin, try the mod instead. Make sure you place the plugin in the plugins folder, or the mod in the mods folder.

Make sure to check if there isn't any other mod that might conflict with Server Redirect, somehow.
