### ISSUE TITLE
Forge 1.19.2-43.3.0 server crash

### ISSUE THREAD

**Issue by paniamaru** [KaiKikuchi/ServerRedirect#29]
Hello, 
I'm having a problem with the ServerRedirect mod when i use the command to forward a user in another server the server crash, I attach the error logs and the versions I'm using , the versions are the same and there is only the mod installed for both servers that i'm using and the client.
 
  Forge 1.19.2-43.3.0
  Mod version: ServerRedirect-ForgeMC19-1.4.5.jar

[crash.txt](https://github.com/KaiKikuchi/ServerRedirect/files/13328123/crash.txt)

Thanks in advance for the help.

**Comment by KaiKikuchi** [comment]
Hello. Please provide the crash log you can find at this location: `/home/container/crash-reports/crash-2023-11-12_14.21.53-server.txt`. Thanks.

EDIT: nevermind, I could reproduce the issue

**Comment by KaiKikuchi** [comment]
Fixed in version [Forge 1.19.x - v.1.4.5a](https://legacy.curseforge.com/minecraft/mc-mods/server-redirect/files/4861998)
