### ISSUE TITLE
Is the prerequisite for using this plug-in in Velocity that the client must be able to enter the lobby correctly?

### ISSUE THREAD

**Issue by kougou888** [KaiKikuchi/ServerRedirect#30]
Is the prerequisite for using this plug-in in Velocity that the client must be able to enter the lobby correctly? I try to use a fabric client to enter the paper lobby, but it will prompt an error that cannot be entered because it is incompatible.

**Comment by KaiKikuchi** [comment]
You need to be able to join the server with your client even if this mod isn't added on the client and the server. This mod does not provide any way to let you join a server with a client if you couldn't before. This mod only provides a way to tell clients that have this mod to connect to a different server address, so you have to have direct connection addresses for each of your servers (ports open toward each server you host, not just the lobby).
