### ISSUE TITLE
Question <=-=> Do my players need this mod?

### ISSUE THREAD

**Issue by TheExotik** [KaiKikuchi/ServerRedirect#31]
My players need to have this mod installed in their game? 
Or can i just use the plugin version inside my "lobby" server?

**Comment by KaiKikuchi** [comment]
Players need to have this mod installed in their game if they want to get transferred to another server. If they do not have the mod, they can still join the server, but when the /redirect command is executed on them, they'll not get transferred. Unless they have "Pixelmon Reforged for Minecraft 1.16.5" in their game client, as Server Redirect is included in Pixelmon Reforged 1.16.5.
