### ISSUE TITLE
Useless once 1.20.5 is out

### ISSUE THREAD

**Issue by Cuteistfox** [KaiKikuchi/ServerRedirect#32]
1.20.5 adds a transfer packet so this mod will not have a use(at least the client part) as you can use the transfer packet in vannila sense 24w03a

**Comment by KaiKikuchi** [comment]
That's a great news, although it took so long to add such a simple thing into the game!

Still, older Minecraft versions will require a mod like this one, not all servers are going to use the latest version as soon as it comes out!
