### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Legomountain14** [KaiKikuchi/ServerRedirect#34]
Sorry to be that guy, but this is a really cool project. Will there be 1.21 support any time soon?

**Comment by KaiKikuchi** [comment]
Which one do you need, Forge or Fabric?

**Comment by Legomountain14** [comment]
Fabric

**Comment by KaiKikuchi** [comment]
Thanks for showing interest in my mod.

I made a Fabric 1.21 version that you can download from the following link:
https://modrinth.com/plugin/server-redirect/version/rwBYXquM
