### ISSUE TITLE
CurseForge

### ISSUE THREAD

**Issue by DV8FromTheCode** [KaiKikuchi/ServerRedirect#4]
Can you upload this mod to CurseForge so it can be used in Twitch/Curse Launcher modpack.

**Comment by KaiKikuchi** [comment]
Done https://minecraft.curseforge.com/projects/server-redirect

**Comment by KaiKikuchi** [comment]
Version 1.4 and higher will be available at this location instead: https://www.curseforge.com/minecraft/mc-mods/server-redirect-new

(they deleted my previous account and I couldn't recover it)
