### ISSUE TITLE
[Request] Expanded permissions

### ISSUE THREAD

**Issue by kencinder** [KaiKikuchi/ServerRedirect#6]
`serverredirect.command.redirect.self` - Allowed to use the command on yourself
`serverredirect.command.redirect.other` -Allowed to use the command on others

This correlates more also with not having to specify yourself either when using the command.

**Comment by KaiKikuchi** [comment]
These will be the new permissions for the subcommands:
- `/redirect [address] *` = serverredirect.command.redirect.all
- `/redirect [address] r=[radius]` = serverredirect.command.redirect.radius
- `/redirect [address] [yourself name or uuid]` = serverredirect.command.redirect.self
- `/redirect [address] [someone else name or uuid]` = serverredirect.command.redirect.others

**Comment by KaiKikuchi** [comment]
Please try this: https://github.com/KaiKikuchi/ServerRedirect/releases/tag/v.1.3.8-BETA1

**Comment by kencinder** [comment]
I've tried using the individual new nodes, as well as going back to `serverredirect.command.redirect` for all of them

The following are the results

`/redirect [address] *` - Works on everyone but sender. Hoping that is intended, I think it's preferable.
`/redirect [address] r=[radius]` - Works the same as *
`/redirect [address] [yourself name or uuid]` - This does NOT work on myself
`/redirect [address] [someone else name or uuid]` - This works fine on others

So the only issue seems to be the use of commands targeting yourself.
